### ISSUE TITLE
Does it work on rave v.2 model?

### ISSUE THREAD

**Issue by gyuchulm** [victor-shepardson/rave-supercollider#4]
I tried to build my own model with v.2
and there are some issues with the build model, and trying to use it in Supercollider. 

I can run the pre-trained model in my SC, but v2 model that I trained are not working in the example code.

I saw your post in Rave GitHub, did your model works in this code?

**Comment by gyuchulm** [comment]
![image](https://user-images.githubusercontent.com/9707888/218247643-0f11eefb-08fc-4fa4-8b81-c6d30dc26fc7.png)

And also, a bit complex is the latent size, is this a buffer size in a training stage? I couldn't find the options of latent size in a rave code. 

I trained the model with rave v.2, and the sound quality is a bit weird, but I can hear the sound. 
But the supercollider has no sounds.

**Comment by victor-shepardson** [comment]
It should be fixed now, apparently RAVE used to export `sampling_rate` but in v2 no longer does, which was crashing rave-supercollider.

**Comment by victor-shepardson** [comment]
> And also, a bit complex is the latent size, is this a buffer size in a training stage? I couldn't find the options of latent size in a rave code.

the maximum latent size is determined by training (see the `fidelity_0.99` curve in tensorboard), and then set to some lower value when you use `rave export` with the `--fidelity` argument
